services:
    app:
        container_name: app
        build: docker
        ports:
            - "9000:80"
        volumes:
            - ./docker/vhosts:/etc/apache2/sites-enabled
            - ./app:/var/www
        restart: always
        networks:
            - rr-net

    database:
        image: mysql:8.3.0
        container_name: database
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: symfony
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - my-db:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            - rr-net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - database
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: password
        restart: always
        ports:
            - 8081:80
        networks:
            - rr-net

    qa:
        image: jakzal/phpqa:php8.2
        container_name: qa
        working_dir: /project
        init: true
        command: sh
        stdin_open: true
        tty: true
        volumes:
            - .:/project:cached
            - qa-tmp:/tmp
networks:
    rr-net:
volumes:
    my-db:
    qa-tmp: